export PATH="$HOME/bin:$HOME/homebrew/bin:$PATH"

export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
export BASH_SILENCE_DEPRECATION_WARNING=1
