#!/usr/bin/env bash

set -eo pipefail

function awshell()
{
    export AWS_DEFAULT_REGION="us-east-1"

    local target=$1
    local extra=""

    while [ $# -gt 1 ]; do
        extra="${extra} ${1}"
        shift
    done

    if [[ $target != i-* ]] ; then
        target="i-${target}"
    fi

    aws ssm start-session --target $target $extra
}

awshell $@
